from Paloma import Paloma
from Golondrina import Golondrina
from Logger import Logger

Logger.setModo("WARN")
print(Logger.getModo())
pepita = Golondrina("Pepita", 2)
print("Tests de Pepita")
print(pepita.getEnergia())
pepita.comer(5)
print(pepita.getEnergia())
pepita.volar(1)
print(pepita.getEnergia())
pepita.comer(20)
print(pepita.getEnergia())
pepita.volar(2)
print(pepita.getEnergia())
pepita.volar(999)  # ejemplo de que no hace nada al no tener suficiente energía
print(pepita.getEnergia())
pepita.setEnergia(10)
print(pepita.getEnergia())
pepita.pescar()
print(pepita.getEnergia())
print("Tests de Pepon")
pepon = Golondrina("Pepón", 1)
print(pepon.getEnergia())
pepon.comer(8)
print(pepon.getEnergia())
pepon.pescar()
print(pepon.getEnergia())
print("Tests de Bombón")
bombon = Paloma("Bombón" )
print(bombon.getEnergia())
bombon.comer(8)
print(bombon.getEnergia())
bombon.defecar()
print(bombon.getEnergia())       